### ISSUE TITLE
export symbols for windows

### ISSUE THREAD

**Issue by aoloe** [aoloe/scribus-plugin-API#12]
all classes in the API need to export the symbols, when compiled with MSVC.

this is currently done by the `SCRIBUS_API` macro (defined in `scribusapi.h`), but that macro "automagically" exports the symbols for the main code and imports them for the plugins.

we need a new macro for importing (and exporting?) the API symbols.

**Comment by aoloe** [comment]
- LINKER_EXPORT and LINKER_IMPORT ?, defined in "linker.h"?

**Comment by Aiena-g** [comment]
Yes this sounds like a good idea. We would need to use LINKER_IMPORT in all plugins in place of SCRIBUS_API to remove the duality of the behaviour of SCRIBUS_API. I noticed that scribus.exe exports 3000 functions. So SCRIBUS_API is used throughout the code more than 3k times. If we are to follow a uniform system we will need to carefully replace all SCRIBUS_API instances with your suggested more explicit macros.

**Comment by Aiena-g** [comment]
I think we should call these DLL_EXPORT and DLL_IMPORT or DLL_LINKER_EXPORT DLL_LINKER_IMPORT as the _declspec(dllexport) and _declspec(dllimport) macros are specifically for DLLs and Windows. I think Scribus uses these in a non standard way for the exe as well.

What are your thoughts?

**Comment by Aiena-g** [comment]
see https://docs.microsoft.com/en-us/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes?view=vs-2017 a simple macro called "DllExport" is defined we could follow a similar naming convention. Its clear and concise.

**Comment by Aiena-g** [comment]
I saw SCRIBUS_API code again though. It seems to include logic for GCC as well as Windows. So how about something like SCRIBUS_API_EXPORT SCRIBUS_API_IMPORT which does all in one shot. I see that this API is ued to manage the symbols correctly in ELFs, .so's on Linux as well as dlls/libs on Windows.

**Comment by aoloe** [comment]
since it's for msvc and gcc... i guess that `LINKER_SYMBOLS_EXPORT` and  `LINKER_SYMBOLS_IMPORT`  might fit.

it's a bit long... but from the name you might get a clue that it's defined in `linker.h`...

i really like to avoid having "scribus-api" in the name, since it's  a misleading name... there is no API defined there...

**Comment by aoloe** [comment]
the existing `PLUGIN_API` does exact that (thanks jean). i've added it to each API class to be exported.

**Comment by Aiena-g** [comment]
If you want a shorter macro you can use LNKR_SYMB_EXPORT LNKR_SYMB_IMPORT
